# Generated by Django 4.2.8 on 2023-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwaybill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppd',
            name='id',
            field=models.AutoField(default=80000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reversepickup',
            name='id',
            field=models.AutoField(default=50000000, primary_key=True, serialize=False),
        ),
    ]
