# Generated by Django 4.2.8 on 2023-12-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customeradditionalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_pincode', models.IntegerField(max_length=8)),
                ('return_pincode', models.IntegerField(max_length=8)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.shipper')),
            ],
        ),
    ]
