# Generated by Django 4.2.8 on 2023-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areamaster',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='areamaster',
            name='status',
        ),
        migrations.RemoveField(
            model_name='areamaster',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='type',
            field=models.IntegerField(choices=[(0, 'Service Centre'), (1, 'Hub'), (2, 'Head Quarter'), (3, 'Processing Centre'), (4, 'Return Center')], default=0, max_length=1),
        ),
    ]
