# Generated by Django 4.2.8 on 2023-12-16 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_transitmastergroup_transitmasterclusterbased'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenterTransitMasterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.servicecenter')),
                ('transit_master_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.transitmastergroup')),
            ],
        ),
    ]
