# Generated by Django 4.2.8 on 2023-12-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_servicecentertransitmastergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_shortcode',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_shortcode',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
