# Generated by Django 4.2.8 on 2023-12-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_city_city_shortcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecenter',
            old_name='type',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
