# Generated by Django 4.2.8 on 2023-12-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_passwordresetotp'),
        ('location', '0007_rename_type_servicecenter_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employeemaster'),
        ),
    ]
