# Generated by Django 4.2.8 on 2023-12-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=5)),
                ('code_description', models.CharField(max_length=200)),
                ('code_redirect', models.IntegerField(blank=True, null=True)),
                ('closure_code', models.BooleanField(default=False)),
                ('parent_code', models.CharField(max_length=5)),
                ('parent_description', models.CharField(max_length=200)),
                ('updation_mode', models.CharField(max_length=10)),
                ('attributed_to', models.CharField(max_length=10)),
                ('failure_off', models.CharField(max_length=10)),
                ('active_status', models.IntegerField(db_index=True, default=1)),
                ('rad_allowed', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
