# Generated by Django 4.2.8 on 2023-12-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
