# Generated by Django 4.2.8 on 2023-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slconfig', '0002_holidaymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('unknown', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
            ],
        ),
    ]
