# Generated by Django 4.2.8 on 2023-12-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('location', '0002_remove_areamaster_added_on_remove_areamaster_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('service_code', models.CharField(max_length=100, unique=True)),
                ('sac_code', models.CharField(max_length=100, unique=True)),
                ('hsn_code', models.CharField(max_length=100, unique=True)),
                ('tax_rate', models.FloatField()),
                ('status', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGSTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.SmallIntegerField(db_index=True, default=0)),
                ('provisional_id', models.CharField(blank=True, max_length=100, null=True)),
                ('default_reg', models.CharField(blank=True, max_length=1, null=True)),
                ('use_for', models.SmallIntegerField(choices=[(0, 'All'), (1, 'WH warehouse'), (2, 'MP vendor')], db_index=True, default=0)),
                ('primary_place_business1', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_place_business2', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_place_business3', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_type', models.SmallIntegerField(db_index=True, default=1)),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_city', to='location.city')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gst.gstservicetype')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_customer', to='customer.customer')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_customer_state', to='location.state')),
            ],
        ),
        migrations.CreateModel(
            name='ClientGSTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('regtration_type', models.SmallIntegerField(db_index=True, default=0)),
                ('gst_state_code', models.CharField(blank=True, max_length=3, null=True)),
                ('provisional_id', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_place_business1', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_place_business2', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_place_business3', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gst.gstservicetype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_ecom_state', to='location.state')),
            ],
        ),
    ]
