# Generated by Django 4.2.8 on 2023-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCancelQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airwaybill_number', models.BigIntegerField(db_index=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
