# Generated by Django 4.2.8 on 2023-12-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('customer', '0001_initial'),
        ('pickup', '0001_initial'),
        ('location', '0003_pincodevirtualdcmapping_adhoccitymapping'),
        ('slconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_pickup', models.BooleanField(default=False)),
                ('return_shipment', models.SmallIntegerField(default=False)),
                ('airwaybill_number', models.BigIntegerField()),
                ('order_number', models.CharField(max_length=20)),
                ('product_type', models.CharField(blank=True, max_length=10, null=True)),
                ('consignee', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_address1', models.CharField(blank=True, max_length=400, null=True)),
                ('consignee_address2', models.CharField(blank=True, max_length=400, null=True)),
                ('consignee_address3', models.CharField(blank=True, max_length=400, null=True)),
                ('consignee_address4', models.CharField(blank=True, max_length=400, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
                ('telephone', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=400, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('collectable_value', models.FloatField(blank=True, null=True)),
                ('declared_value', models.FloatField(blank=True, null=True)),
                ('actual_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('volumetric_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('length', models.FloatField(blank=True, default=0.0, null=True)),
                ('breadth', models.FloatField(blank=True, default=0.0, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('status_type', models.IntegerField(blank=True, default=0, null=True)),
                ('remark', models.CharField(blank=True, max_length=400, null=True)),
                ('expected_dod', models.DateTimeField(blank=True, null=True)),
                ('ref_airwaybill_number', models.BigIntegerField(blank=True, null=True)),
                ('rts_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('rts_date', models.DateTimeField(blank=True, null=True)),
                ('inscan_date', models.DateTimeField(blank=True, null=True)),
                ('rts_status', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('rd_status', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('rto_status', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('sdd', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('rejection', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('sdl', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tab', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('chargeable_weight', models.FloatField(blank=True, default=0, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_ships', to='billing.billing')),
                ('current_sc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_sc', to='location.servicecenter')),
                ('manifest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_location', to='location.servicecenter')),
                ('original_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_origin_sc', to='location.servicecenter')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_pickup', to='pickup.pickupregistration')),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slconfig.shipmentstatusmaster')),
                ('service_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_sc', to='location.servicecenter')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PincodeEmbargoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('pincode', models.IntegerField(db_index=True, default=0)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pincode_type', models.CharField(blank=True, max_length=10, null=True)),
                ('embargo_status', models.IntegerField(db_index=True, default=0)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
