# Generated by Django 4.2.8 on 2023-12-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiShipments',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apishipment', serialize=False, to='servicecenter.shipment')),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('upload_type', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('shipment_type', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('preferred_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('preferred_delivery', models.BooleanField(default=False)),
                ('transport_type', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('reason_for_reverse_pickup', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_information', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferShipments',
            fields=[
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prefershipment', serialize=False, to='servicecenter.shipment')),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('mode', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('time_from', models.TimeField(blank=True, db_index=True, null=True)),
                ('time_to', models.TimeField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
