# Generated by Django 4.2.8 on 2023-12-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slconfig', '0003_addonservices'),
        ('servicecenter', '0002_apishipments_prefershipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('addonservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentservices_addon', to='slconfig.addonservices')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentservices_shipment', to='servicecenter.shipment')),
            ],
        ),
    ]
