# Generated by Django 4.2.8 on 2023-12-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0005_shipmenthistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentHistory',
        ),
    ]
