# Generated by Django 4.2.8 on 2023-12-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_pincode_updated_by'),
        ('servicecenter', '0007_shipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenthistory',
            name='current_sc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hist_current_sc', to='location.servicecenter'),
        ),
    ]
