# Generated by Django 4.2.8 on 2023-12-22 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0008_shipmenthistory_current_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenthistory',
            name='added_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipmenthistory',
            name='updated_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
