# Generated by Django 4.2.8 on 2023-12-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0009_alter_shipmenthistory_added_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_info_key', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('add_info_value', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_shipment', to='servicecenter.shipment')),
            ],
        ),
    ]
