# Generated by Django 4.2.8 on 2023-12-28 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0010_additionalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenthistory',
            name='partition_month',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
