# Generated by Django 4.2.8 on 2023-12-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
