# Generated by Django 4.2.8 on 2023-12-11 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_usersecretcredentials_delete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Account', 'Account'), ('Customer Service', 'Customer Service'), ('Customer Service Accounts', 'Customer Service Accounts'), ('Finance', 'Finance'), ('HR', 'HR'), ('Hub', 'Hub'), ('IT', 'IT'), ('Operations', 'Operations'), ('Sale', 'Sale')], max_length=150)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=10, null=True)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('address3', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(max_length=60)),
                ('login_active', models.IntegerField(default=0, max_length=2)),
                ('staff_status', models.IntegerField(default=0, max_length=2)),
                ('allow_concurent_login', models.IntegerField(blank=True, choices=[(0, 'Allow Concurrent Login (Required)'), (0, 'False'), (1, 'True')], default=0, max_length=2, null=True)),
                ('query_limit', models.IntegerField(blank=True, default=50, max_length=5, null=True)),
                ('ebs', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usersecretcredentials',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserLoginOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(db_index=True, max_length=30)),
                ('active_status', models.BooleanField(db_index=True, default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedOn', models.DateTimeField(auto_now=True, db_index=True)),
                ('resend_count', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_pattern', models.CharField(db_index=True, max_length=200)),
                ('addedOn', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedOn', models.DateTimeField(auto_now=True, db_index=True)),
                ('active_status', models.BooleanField(db_index=True, default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employeemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employeemaster')),
            ],
        ),
        migrations.CreateModel(
            name='OutscanEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(db_index=True, default=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('intime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField(blank=True, db_index=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employeemaster')),
            ],
        ),
        migrations.CreateModel(
            name='OldPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_pattern', models.CharField(db_index=True, max_length=200)),
                ('addedOn', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedOn', models.DateTimeField(auto_now=True, db_index=True)),
                ('active_status', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usertype'),
        ),
        migrations.CreateModel(
            name='EmployeeAdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_info_key', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('add_info_value', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activation_status', models.BooleanField(db_index=True, default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employeemaster')),
            ],
        ),
        migrations.CreateModel(
            name='DisablePasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_pattern', models.CharField(db_index=True, max_length=30)),
                ('active_status', models.BooleanField(db_index=True, default=True)),
                ('addedOn', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedOn', models.DateTimeField(auto_now=True, db_index=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='authentication.employeemaster')),
            ],
        ),
    ]
