# Generated by Django 4.2.8 on 2023-12-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('authentication', '0005_department_employeemaster_usertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='service_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.servicecenter'),
        ),
    ]
