# Generated by Django 4.2.8 on 2023-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_employeemaster_service_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daywise_otp', models.BooleanField(db_index=True, default=False)),
                ('otp_with_pass', models.BooleanField(db_index=True, default=False)),
                ('otp_without_pass', models.BooleanField(db_index=True, default=False)),
                ('without_otp', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
