# Generated by Django 4.2.8 on 2023-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_otpconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpconfig',
            name='without_otp',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
