# Generated by Django 4.2.8 on 2023-12-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_otpconfig_without_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloginotp',
            old_name='active_status',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='otpconfig',
            name='otp_without_pass',
        ),
        migrations.RemoveField(
            model_name='otpconfig',
            name='without_otp',
        ),
    ]
