# Generated by Django 4.2.8 on 2023-12-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('authentication', '0009_rename_active_status_userloginotp_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('url', models.CharField(db_index=True, max_length=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(db_index=True, max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='api_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('url', models.CharField(db_index=True, max_length=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(db_index=True, max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='authentication.department')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertype', to='authentication.department')),
            ],
        ),
    ]
