# Generated by Django 4.2.8 on 2023-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_menu_icon_alter_submenu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='icon',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
