# Generated by Django 4.2.8 on 2023-12-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_menu_icon_alter_submenu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertype', to='authentication.usertype'),
        ),
    ]
