# Generated by Django 4.2.8 on 2023-12-18 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0013_alter_role_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(db_index=True, max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedOn', models.DateTimeField(auto_now=True, db_index=True)),
                ('resend_count', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
