# Generated by Django 4.2.8 on 2023-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
