# Generated by Django 4.2.8 on 2023-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_jsonschema_alter_employeemaster_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='sub_menu',
            field=models.ManyToManyField(db_index=True, null=True, related_name='submenu', to='authentication.submenu'),
        ),
    ]
