# Generated by Django 4.2.8 on 2023-12-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_gst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gst.customergstregistration'),
        ),
    ]
