# Generated by Django 4.2.8 on 2023-12-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('servicecenter', '0001_initial'),
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='demarrage_shipments',
            field=models.ManyToManyField(related_name='billing_demarrage_shipments', to='servicecenter.shipment'),
        ),
        migrations.AddField(
            model_name='billing',
            name='ecom_gst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gst.clientgstregistration'),
        ),
        migrations.AddField(
            model_name='billing',
            name='shipments',
            field=models.ManyToManyField(related_name='ship_bills', to='servicecenter.shipment'),
        ),
    ]
